name: Deploy Backend to FTP Staging

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy PHP Backend
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./backend/ # This is the directory on your local GitHub repository to upload
        server-dir: /httpdocs/staging/ # This is the target directory on your FTP server
        # Optional: Set to 'true' to delete files on the server that are not present locally. Use with caution.
        # dangerous-clean-slate: true
        # Optional: Exclude files/folders from being uploaded. By default, .git* and node_modules are excluded.
        # exclude: |
        #   ./backend/vendor/**
        #   ./backend/storage/**